--
--------------------------------------------------------------------------------
--         File:  main-1.lua
--
--        Usage:  ./main-1.lua
--
--  Description:  第一个主程序
--
--      Options:  ---
-- Requirements:  ---
--         Bugs:  ---
--        Notes:  ---
--       Author:  YOUR NAME (), <>
-- Organization:  
--      Version:  1.0
--      Created:  2019年08月17日
--     Revision:  ---
--------------------------------------------------------------------------------
--

dofile("")
